### ISSUE TITLE
expose state or elemets

### ISSUE THREAD

**Issue by maxigit** [rl-king/elm-inview#2]
This package is brilliant but I need to access `State` to get dimension of an element.
I could create my own port but that would mean subscribing twice to the same event (once for InView once for myself). An easy fix (which would probably be better than exposing State) is to change the type signature of `checkCustom` to allow any type (instead of just Bool)

   checkCustom : (Viewport -> Element -> a) -> String -> State -> Maybe a

This way I could return the size of the element or part of the view etc ...

**Comment by rl-king** [comment]
I somehow completely missed this issue, but also started working on 2.0.0 this weekend with this exact change :).

Have a look at https://github.com/rl-king/elm-inview/pull/3, feedback is welcome. I'll probably release it tomorrow.

**Comment by rl-king** [comment]
Apparently I wasn't "watching" this repo.

**Comment by maxigit** [comment]
That's brilliant. I have a quick look at the changes and they look great (I'm not usually a big fan of name changes but I think in that case they are much meaningful indeed).
I'm working on something else right now that it's not urgent, but I definitely migrate to the new version once it's released.

Thankx

**Comment by maxigit** [comment]
I finally migrated to version 2.0.0 and it works well. Many thanks.
