### ISSUE TITLE
Problem downloading package

### ISSUE THREAD

**Issue by numblock** [rl-king/elm-inview#5]
Getting error in all our projects:
```
I was trying to download the source code for rl-king/elm-inview 2.0.0, so I
tried to fetch:
    https://github.com/rl-king/elm-inview/zipball/2.0.0/
But it came back as 300 Multiple Choices
```
Is this something that you can fix on your side?

**Comment by rl-king** [comment]
My commit closed this by accident.

I'll release a minor version bump, maybe that fixes the issue.

**Comment by rl-king** [comment]
It seems to be fixed now. 

Not sure why this issue came up all of a sudden... I might have pushed two 2.0.0 tags or something when I was creating a release back then, and GitHub recently updated the response to requests of tags in a way elm doesn't know how to handle.

**Comment by numblock** [comment]
Fixed, thanks for your swift response!
Hope that you are well! 👍 😄
